# Configuration for python-kacl (kacl-cli): validates the CHANGELOG against
# Keep a Changelog and generates the version comparison links.
kacl:
  file: CHANGELOG.md
  allowed_header_titles:
    - Changelog
  allowed_version_sections:
    - Added
    - Changed
    - Deprecated
    - Removed
    - Fixed
    - Security
  default_content:
    - All notable changes to this project will be documented in this file.
    - The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
  links:
    auto_generate: True
    host_url: https://git.lichtenwalter.site/rlichten/vcp
    compare_versions_template: '{host}/compare/v{previous_version}...v{version}'
    unreleased_changes_template: '{host}/compare/v{latest_version}...main'
    initial_version_template: '{host}/releases/tag/v{version}'
